kadai03
shinonome-inc/mobile_Kuboko pull request #8
Opened 2020-06-23 16:27 UTC by kubokoHappy

レビューお願いします

2020-06-24 01:09 UTC, taitai9847 commented on LeapYearApp/LeapYearApp2/LeapYearApp2/ViewController.swift
> +
26,27行目の
```
@IBOutlet weak var result: UILabel!
@IBOutlet weak var year: UITextField!
```
はここに書いた方がいい！

2020-06-24 01:16 UTC, mcz9mm requested changes
コメントしました！

2020-06-24 01:16 UTC, mcz9mm commented on LeapYearApp/LeapYearApp2/LeapYearApp2/ViewController.swift
> +    @IBOutlet weak var year: UITextField!
`@IBOutlet`はクラス変数で慣習的にクラス内の頭に書いておくことが多いかな。
ざっくり区分けすると↓
```
class ViewController: UIViewController {
    // IBOutletや変数等

    // viewDidLoadなどのViewControllerのライフサイクル

    // IBAction, func等
}

```

2020-06-24 01:16 UTC, mcz9mm commented on LeapYearApp/LeapYearApp2/LeapYearApp2/ViewController.swift
> +        if let y = Int(year.text!) {
if letしてるのは良いですが惜しい！
`Int(year.text!)`で「!」を使わずに修正してみましょう。

まずはyear.textの値をオプショナルアンラップして取り出し、
その取り出した値(String)をIntへ変換できるかどうかオプショナルアンラップする流れになります。
(要はnilになる可能性の箇所が２つある感じ)

if let文はカンマ区切りで複数条件とアンラップが可能です。
```
if 
  let a = hoge,
  let b = Int(a) {
    // a, bはnilではない
}
```

2020-06-24 01:16 UTC, mcz9mm commented on LeapYearApp/LeapYearApp2/LeapYearApp2/ViewController.swift
> +            if (r == true) {
if文であればboolはそのまま使えるよ

```
if r {

}
```

でも良いし、if文の条件に直接boolを返すメソッドを入れても良いかな
```
if isLeap(year: y) {

}
```

2020-06-26 14:00 UTC, mcz9mm approved these changes
OKです！

2020-06-26 14:00 UTC, merged